**SERVO PREDICTION USING LINEAR REGRESSION**

Description: This dataset provides information about a servo motor mechanism, capturing various parameters and their corresponding classes. Each entry in the dataset represents a specific configuration of the servo motor mechanism along with associated attributes.

**importing liabrary**

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**IMPORTING DATA SET**

In [3]:
df=pd.read_csv('/content/Servo Mechanism.csv')

**DATA VISUALIZATION**

In [4]:
df.head()

Motor Screw  Pgain  Vgain  Class
0     E     E      5      4      4
1     B     D      6      5     11
2     D     D      4      3      6
3     B     A      3      2     48
4     D     B      6      5      6

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Motor   167 non-null    object
 1   Screw   167 non-null    object
 2   Pgain   167 non-null    int64 
 3   Vgain   167 non-null    int64 
 4   Class   167 non-null    int64 
dtypes: int64(3), object(2)
memory usage: 6.6+ KB


In [6]:
df.describe()

Pgain       Vgain       Class
count  167.000000  167.000000  167.000000
mean     4.155689    2.538922   21.173653
std      1.017770    1.369850   13.908038
min      3.000000    1.000000    1.000000
25%      3.000000    1.000000   10.500000
50%      4.000000    2.000000   18.000000
75%      5.000000    4.000000   33.500000
max      6.000000    5.000000   51.000000

**GETING COLUMN**

In [7]:
df.columns

Index(['Motor', 'Screw', 'Pgain', 'Vgain', 'Class'], dtype='object')

In [32]:
df.replace({'Motor':{'A':0,'B':1,'C':3,'D':4,'E':5}},inplace=True)



In [33]:
df.replace({'Screw':{'A':0,'B':1,'C':3,'D':4,'E':5}},inplace=True)

In [34]:
y=df['Class']
x=df[['Motor','Screw', 'Pgain', 'Vgain']]


In [35]:
from sklearn.model_selection import train_test_split
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.7 ,random_state=2529)

In [36]:
x_test.shape,x_train.shape,y_test.shape,y_train.shape

((50, 4), (117, 4), (50,), (117,))

In [37]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [40]:
lr.coef_

array([ -1.17527569,  -2.23271339, -16.35824442,   5.65234266])

In [48]:
y_pre=lr.predict(x_test)

In [53]:
y_test

array([25.73487766, 13.50124388, 17.3678871 , 15.73395728, 28.43689645,
       31.96272352,  7.26076891, 38.20319849, 17.96667067, 23.38432628,
       28.54309425, 12.09029221, 29.02502876,  6.08549322, -0.73048495,
       12.90246032, 22.78455379, 29.61217214,  4.18195579,  1.50222844,
       32.44465803, 21.13898378, 17.37952729,  2.79534212, 29.71836995,
        9.85757882, 24.55960197, 34.67737142, 25.14674535, 21.73875627,
       46.07661437, 35.37071261, 23.48953516, 25.01726718, 24.20714564,
       15.95693543, 23.03186995, 17.14385131, 17.13221113, 32.31517985,
       40.20023591, 13.95989802, 12.32596819, 30.21194463, 36.89844463,
       18.90627038, 27.48565655, 21.6092781 ,  9.25780633, 25.61703967])

In [49]:
y_pre

array([25.73487766, 13.50124388, 17.3678871 , 15.73395728, 28.43689645,
       31.96272352,  7.26076891, 38.20319849, 17.96667067, 23.38432628,
       28.54309425, 12.09029221, 29.02502876,  6.08549322, -0.73048495,
       12.90246032, 22.78455379, 29.61217214,  4.18195579,  1.50222844,
       32.44465803, 21.13898378, 17.37952729,  2.79534212, 29.71836995,
        9.85757882, 24.55960197, 34.67737142, 25.14674535, 21.73875627,
       46.07661437, 35.37071261, 23.48953516, 25.01726718, 24.20714564,
       15.95693543, 23.03186995, 17.14385131, 17.13221113, 32.31517985,
       40.20023591, 13.95989802, 12.32596819, 30.21194463, 36.89844463,
       18.90627038, 27.48565655, 21.6092781 ,  9.25780633, 25.61703967])

In [52]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pre)

0.0